spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: member
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

logging:
  level:
    org.hibernate.SQL: debug

consumer:
  topic1:
    name: rental_rent
  topic2:
    name: rental_return
  topic3:
    name: overdue_clear
  groupid:
    name: member
kafka:
  bootstrapAddress: localhost:9092